### ISSUE TITLE
Failure on withWolkenkit()

### ISSUE THREAD

**Issue by ericklind** [thenativeweb/wolkenkit#108]
I've been trying to use this based on the example in the README.  I keep getting this error:
`index.js:1452 Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.in withWolkenkit (at src/index.jsx:9)`

My index.jsx looks like this:

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import Application from 'wolkenkit-react';
import App from './App';

ReactDOM.render(
    (<Application host={'local.wolkenkit.io'} port={3500}>
        <App />
    </Application>)
    , document.getElementById('root'));
```

App.jsx:
```
import * as React from 'react';
import Home from './containers/Home.jsx';
import { withWolkenkit } from 'wolkenkit-react';

class App extends React.Component {
  render() {
    return (
                <Home ></Home>
          );
  }
}
export default withWolkenkit(App);
```

Any idea how to move past this?

**Comment by mattwagl** [comment]
@ericklind Which README or repo are you referring to? There currently is the JavaScript SDK called [wolkenkit-client-js](https://github.com/thenativeweb/wolkenkit-client-js). This one is stable but it does not include any React related code, since we want to keep this framework agnostic.

Then there is  [wolkenkit-react](https://github.com/thenativeweb/wolkenkit-react) which actually started out as a package created by the community. I think this is what you might have found and which might have caused the confusion. So sorry for this inconvenience! The original maintainer transferred it to us and we have been been working on it since without having published it to npm. So when you install it from npm you get the `0.5.0` version which is still an old one. If you look at github you see the docs of the current master branch. Sorry for not making this totally clear on the repo!

@goloroden So I think we should create a new version and publish it to npm and maybe document its relationship wioth the original SDK? But the [npm package](https://www.npmjs.com/package/wolkenkit-react) has not been transferred, yet. I think that's why we haven't published until now. Should we contact the original author?

**Comment by goloroden** [comment]
@mattwagl Sorry, that's my fault … @ericklind originally posted this in the [wolkenkit-react](https://github.com/thenativeweb/wolkenkit-react) repository, but I moved it here so that we have all the issues in one place. Sorry that the issue lost context this way :-(

Regarding the issues on the React package … IIRC we discussed that we needed to take another look at React hooks, before releasing that module into the wild, didn't we?

Regarding npm, I will contact the original author and ask him if he could transfer the repo to us.

**Comment by mattwagl** [comment]
I had the ability to play with React hooks inside wolkenkit-console. It‘s really interesting. But it’s still in beta, so I‘m not sure if we should wait for the API to stabilize. Especially if we want to support current versions of React. Not everybody is able to upgrade and use the alpha version. 

@ericklind: A quick temporary fix for you would be to install `thenativeweb/wolkenkit-react` instead of the npm version.

**Comment by goloroden** [comment]
Okay … then let's way for the reply of the original author, and then see whether to publish another `0.x` version to npm 😊

**Comment by goloroden** [comment]
@mattwagl Done 😄 

See the collaborators section on https://www.npmjs.com/package/wolkenkit-react

Shall we talk about this tomorrow?

**Comment by goloroden** [comment]
@mattwagl I think it was too early to close this one, as we do not yet have published a new version of `wolkenkit-react`. Hence, I reopened it.

**Comment by mattwagl** [comment]
Fixed tests, updated the license check for this module, updated deps, released new version and [published it to npm](https://github.com/thenativeweb/wolkenkit-react/). So we should now be able to iterate quicker on this thingy. New version is 0.1.1. @ericklind that should hopefully fix your problem. Gonna close this now. Feel free to open a new issue if new problems should occur.
