### ISSUE TITLE
Add babel support for transpiling application code

### ISSUE THREAD

**Issue by gossi** [thenativeweb/wolkenkit#113]
### What is this concept about?

Adding babel to the server part of wolkenkit. Expect the source to be available in `src/`. Whenever `wolkenkit start` is run, it will run `babel` first, tranpiling the source to a intermediate folder (atm this must be `server`) and boot up wolkenkit. Wolkenkit itself can be very agnostic about how babel is configured, that is up to the enduser. He may use typescript or ESnext features. Since babel is configurable with plugins, that's up to the end user to install or write them to use whatever transpiling they want.

PS: At least babel should be shipped with esmodules support ;)
PS2: There can be templates for different flavors (e.g. Typescript)

### What issues need to be clarified to complete this concept?

- [ ] Where and when should we run babel?
- [ ] Do we need a different folder structure for the backend?

### What else should we know?

Proof-of-Concept is available: https://github.com/gossi/spomoda/tree/master/server

**Comment by goloroden** [comment]
Right now, when starting a wolkenkit application, we are [building the application's images](https://github.com/thenativeweb/wolkenkit/blob/8a0f24e8f9c5b8a03361bfb0cc7b9c0110ed59ed/src/wolkenkit/commands/shared/buildImages.js#L51), which also copies the application's source code into the image. In this step, we could simply run `babel`, so that the user does not need to install and maintain babel on their own – instead wolkenkit itself would be able to run babel.

This then would also mean that we do not necessarily have to change the folder structure, since there is no need for a `src` folder *and*  a `server` folder: One would be enough, and the transpiled version would only be available inside of the image.

@gossi What do you think about this?

**Comment by gossi** [comment]
Sounds good. Absolutely there should be only one folder (I prefer `src` :p and aligns more with comon rules, see also #115) and the transpiled code would go to the image.

**Comment by goloroden** [comment]
In v4 we are going to support TypeScript and JavaScript, and when someone writes their wolkenkit application using TypeScript, we compile it by using `tsc`.

I think that this fulfills the intention behind this issue, so I am going to close this one.
