### ISSUE TITLE
Improve the folder structure of wolkenkit applications

### ISSUE THREAD

**Issue by gossi** [thenativeweb/wolkenkit#114]
### What is this concept about?

When running `wolkenkit init` at the moment, it will create the server package in the root and the client package as a subfolder. That way those two are not independent from each other. Dealing with subpackages in yarn/npm is not very ideal and can easily lead to problems. Moving the root package.json to the `server/` folder will help.
To support this idea, maybe have the idea of [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) in mind. Even if it is not very applicable to these kind of projects (since server and client won't share many dependencies), it's still a widely accepted way of structuring repos and keeping them clean (also tools like lerna support this).

@goloroden mentioned on slack you expect the `wolkenkit` in the root `package.json`. That still can be the case, you can create a root `package.json` with a `wolkenkit` entry, that just takes the path to the server related `package.json` and you are good to hop your way over there (also a very common case for many projects I've worked with).

The root `package.json` can look like this:

```
{
  "name": "my-name",
  "private": true,
  "wolkenkit": "path/to/server"
}
```

### What else should we know?

Aligns nicely with #113
Proof-of-Concept is available: https://github.com/gossi/spomoda/tree/master/server

**Comment by goloroden** [comment]
@gossi Thanks for your suggestions, I will think about this (but this may take a few days). I will get back to you!

**Comment by goloroden** [comment]
@gossi We have been discussing this, and we have come to the conclusion that we are going to stick with the current folder structure.

I'll explain why: Other than the sample applications suggest, we think that you should separate the server and the client into different *repositories*, not only different directories. Otherwise it's impossible to manage tags for the server and the client in an independent way, and both are always tied to each other. Especially if you have more than one client (think web, mobile, …) this becomes cumbersome and annoying.

In the sample applications we put the client into a subdirectory to make it easy to get started, but we wouldn't recommend this as best practice. Different applications (such as client and server) should go into different repositories.

If you organize your code like this, you don't have the mentioned problems with multiple `package.json` files, as each project has its own dedicated space with a single `package.json` file.

The option to introduce a third `package.json`, which then points to the `server` folder is technically viable, but feels wrong: Especially in those cases where you don't have a client in the same repo, this soon starts to become annoying, because you now *have* to deal with at least of them all the time.

From our point of view, It also doesn't make too much sense to have the `server` folder configurable, as we strongly believe in convention over configuration (and this is a pattern wolkenkit heavily relies upon), and we don't want to break with that.

Hence, to cut a long story short, we are going to stick with the current folder structure.

**Comment by gossi** [comment]
It took me a while to figure out, but this is Specification vs Convention. So let me define in short by what I mean with the two:

Specification: How the `server/` *must* look like to be loaded into the docker container

Convention: How your source code is looking to be handled by the `wolkenkit` cli

At the moment, since there is not much conversion between the two, it is convention = specification. However, since there is a cli tool in place both should be treated respectively (and if not, this confusion is happening). Second is the sample blueprint that got applied when running `wolkenkit init` that further contributes to that confusion (I didn't specify the blueprint but it was used - why?).
Thanks to your explanation, I now understand, that the created repo is actually used for server only - that helps and I will account this with the following observations.

So, here are things that are confusing with the current folder structure:

- If the project is meant to be only for server purpose, why must still be everything in the `server/` folder? There is no reason for existence of the `server/` folder other than that it must comply with the spec. Everything inside the `server/` folder can be in the root of the project 🤷‍♂️ 
- I've never been a fan of mixing source code with assets into the same folder and it is not even a good convention either. A good convention here is to keep things separated, that's why I did it. Other assets for a server could be a configuration folder or similar. A good convention here would be to define those slots and how they can be configured, so wolkenkit cli does know where to pick it up and generated the `server/` folder according to the spec for it.
- `wolkenkit init` is basically the entry point for a new user, which is nice to scaffold everything needed. However, as already explained a little above, it did things I didn't expected. For ember (which is the framework I'm using on the frontend side) I wrote a cli tool, to get beginners onboard while also supporting the needs of experienced users. You can find it here: [https://github.com/gossi/ember-cli-create](ember-cli-create). Basically it prompts you with a wizard at first and afterwards runs the commands appropriately parametrized. It is an idea, I wanted to share, maybe something that can help here, too.

I want to again highlight the build step of a convention-based repo/package structure to a spec-based `server/` folder using the power of the cli tool, since I do have a feeling this isn't under-emphasized and what this ticket is mainly about. It looks like at the moment this step isn't present at all. At the moment this hinders developers to select their own flavored style of javascript (e.g. typescript #45) but bound to the one that comes with wolkenkit/node. Reversing this sentence: 
A proper build step is required to leverage the javascript tooling ecosystem!

In fact the absense of a convention for a build step leads to wild wild west configurations for each projects looking different that want that sort of step (as I did) and will probably hit hardcoded (unoverridable) configuration parameters, e.g.: https://github.com/thenativeweb/wolkenkit/blob/653271ce269f8e833fbf800026201a4fe4dd9585/src/wolkenkit/commands/shared/validateCode.js#L22-L32
(I do hit them, because my transpiled code wasn't verified by these parameters, although was looking good)

Gladly, we have different views on the toolkit and as a newcomer I hope sharing these experiences and solutions I've seen in other projects for this can be used to make this library easier to use :)

**Comment by goloroden** [comment]
Thanks for your detailed answer, and I will try to answer your questions:

> If the project is meant to be only for server purpose, why must still be everything in the server/ folder? There is no reason for existence of the server/ folder other than that it must comply with the spec. Everything inside the server/ folder can be in the root of the project

Unfortunately not 😉

The reason for still having the `server` folder is to allow you to add images, documentation, and other stuff to the repository, that logically belongs to the server, but does not add to the things that are needed at runtime. Having a dedicated `server` folder allows us to only put this one into the Docker image, which helps to keep the Docker image small. If we put everything in the root folder, we'd need a mechanism for you to manage which files to include and which not to: This is more cumbersome than just saying: Everything that shall go into the Docker image has to be in `server`.

> I've never been a fan of mixing source code with assets into the same folder and it is not even a good convention either. A good convention here is to keep things separated, that's why I did it. Other assets for a server could be a configuration folder or similar. A good convention here would be to define those slots and how they can be configured, so wolkenkit cli does know where to pick it up and generated the server/ folder according to the spec for it.

Yes and no. I'd agree that mixing them is probably not the best option, but there is another pattern we tried to follow when developing wolkenkit. We want things to be simple, and there should be exactly one way to use for some things. Everything that you make configurable is a new source of potential errors. We think that having the convention I described before (everything that should go to the Docker image …) has more advantages and is less error-prone than giving users the opportunity to create more or less arbitrary folders, and then having to configure what goes where.

> wolkenkit init is basically the entry point for a new user, which is nice to scaffold everything needed. However, as already explained a little above, it did things I didn't expected. For ember (which is the framework I'm using on the frontend side) I wrote a cli tool, to get beginners onboard while also supporting the needs of experienced users. You can find it here: ember-cli-create. Basically it prompts you with a wizard at first and afterwards runs the commands appropriately parametrized. It is an idea, I wanted to share, maybe something that can help here, too.

You are right, in that the sample apps (including the default init template) are confusing here, and we should make it more obvious why it is handled in those repos as it is. I understand the idea of an assistant that helps you get started, but in the end this still means that you have a number of choices that you can mix up and that can result in errors. If you can't configure something, you can't do it wrong. Yes, if you handle things like that, you will probably not find a solution that is 100% perfect for everyone, but I'd rather have a solution that is great for 80% of the people, than one where 100% of the people have to deal with errors popping up due to configuration errors.

To underline our way of thinking here I think a good read is [Choices = Headaches](https://www.joelonsoftware.com/2006/11/21/choices-headaches/) by Joel Spolsky.

And please don't get me wrong: I'm very happy about your feedback, I don't want to put you down. But we have to find a way that works best for most of our users, and from our experience having less configuration options is better.

**Comment by gossi** [comment]
Ah, I truly do not understand all parts then, but that's good I'll not be the only one and getting this answers helps to improve docs.
 
> The reason for still having the `server` folder is to allow you to add images, documentation, and other stuff to the repository, that logically belongs to the server, but does not add to the things that are needed at runtime. Having a dedicated `server` folder allows us to only put this one into the Docker image, which helps to keep the Docker image small. If we put everything in the root folder, we'd need a mechanism for you to manage which files to include and which not to: This is more cumbersome than just saying: Everything that shall go into the Docker image has to be in `server`.

Hmm, for me it would be only to have one `server/` folder in the root of the project (along with some project describing config files, e.g. eslint, babel, package.json, etc.). Everything else I'd have would be in the server folder and then its existence is truly questionable. Also, since you mentioned earlier, it is only for server (I read backend) purposes, all the assets you mentioned I'd put into the frontend. So I was wondering how your project would look like with else stuff. Can you explain those use-cases a bit more? I'm interessted

> 
> > I've never been a fan of mixing source code with assets into the same folder and it is not even a good convention either. A good convention here is to keep things separated, that's why I did it. Other assets for a server could be a configuration folder or similar. A good convention here would be to define those slots and how they can be configured, so wolkenkit cli does know where to pick it up and generated the server/ folder according to the spec for it.
> 
> Yes and no. I'd agree that mixing them is probably not the best option, but there is another pattern we tried to follow when developing wolkenkit. We want things to be simple, and there should be exactly one way to use for some things. Everything that you make configurable is a new source of potential errors. We think that having the convention I described before (everything that should go to the Docker image …) has more advantages and is less error-prone than giving users the opportunity to create more or less arbitrary folders, and then having to configure what goes where.

I wouldn't make it configurable but put up conventions how things would be structured. See ember for example, it is probably *the* framework when it comes to convention over configuration. Wolkenkit looks like the counterpart to it on the backend side ;)
  
> You are right, in that the sample apps (including the default init template) are confusing here, and we should make it more obvious why it is handled in those repos as it is. I understand the idea of an assistant that helps you get started, but in the end this still means that you have a number of choices that you can mix up and that can result in errors. If you can't configure something, you can't do it wrong. Yes, if you handle things like that, you will probably not find a solution that is 100% perfect for everyone, but I'd rather have a solution that is great for 80% of the people, than one where 100% of the people have to deal with errors popping up due to configuration errors.

I could imagine one question here, where you can select two answers:

```
Q: What kind of wolkenkit would you like to init?
[ ] I am new to wolkenkit, please get me started
[ ] I know wolkenkit, please setup everything for me
```

On the first answer would install the beginner blueprint, while on the second one those dummy objects would be left out (anyway the experienced wolkenkits users first job is to delete all those *noisy* files in their project - not a cool DX).

 
> To underline our way of thinking here I think a good read is [Choices = Headaches](https://www.joelonsoftware.com/2006/11/21/choices-headaches/) by Joel Spolsky.

To me: No choice = no TS = Headache 😛 SCNR 

> And please don't get me wrong: I'm very happy about your feedback, I don't want to put you down. But we have to find a way that works best for most of our users, and from our experience having less configuration options is better.

Happy to share it 😃

**Comment by goloroden** [comment]
> Hmm, for me it would be only to have one server/ folder in the root of the project (along with some project describing config files, e.g. eslint, babel, package.json, etc.). Everything else I'd have would be in the server folder and then its existence is truly questionable. Also, since you mentioned earlier, it is only for server (I read backend) purposes, all the assets you mentioned I'd put into the frontend. So I was wondering how your project would look like with else stuff. Can you explain those use-cases a bit more? I'm interessted

Why should you put documentation, images, … that refer to the server (i.e. backend) into the repository of the frontend? Sometimes, if you build a system that *only* consists of an API (and no UI) you don't have any other choice.

The basic structure of a wolkenkit app repo should be like this:

```
/
  server/
    flows/
    readModel/
    writeModel/
    …/
    anything-else-required-by-the-server/
    …/
  documentation/
  images/
  …/
  anything-else-not-required-by-the-server/
  …/
  package.json
```

> I wouldn't make it configurable but put up conventions how things would be structured.

What do you mean by that? Isn't "put everything that the server needs to execute into the `server` directory" exactly that? If we get away from this, how would the CLI know which directories to use, and which not to use?

Regarding the choices in the `init` command: I like that 😊 
I'll add an issue for that.
