### ISSUE TITLE
Path to certificate has to begin with server/

### ISSUE THREAD

**Issue by gossi** [thenativeweb/wolkenkit#115]
### What is this bug about?

In `package.json` for the server, the `certificate` property for an `identityProvider` takes a path as value. However, this path has to begin with `server/`. I tried separating source and resources and pointed the certificate to my resources folder (= `res/`) which didn't work (value was `/res/keys/auth0`). I updated my yarn script to copy those resources into my server folder which is then picked up.

### What steps are needed to reproduce the bug?

- Well, already explained above

### What is the expected result?

Pick up the cert at the location I configured, don't expect it anywhere else

### What is the actual result?

Couldn't find the cert

### What else should we know?

3.0.0

**Comment by goloroden** [comment]
Thanks for bringing up this issue. As already explained in #114 the folder structure has some reasons behind it. In addition to the explanations given there, I would like to explain that the `server` folder is actually the only folder we bundle into the Docker images of the application. This is why the `keys` directory (or however you name it) has to be inside of `server`.

We don't want to make this configurable, as the benefits you gain are probably way smaller than the new source of potential errors (because then we would need to dynamically decide what to bundle, what not, people would need to configure it, …). If you contrast this to the simple rule "everything the server needs has to be below the `server` directory", the latter approach is way easier and less error-prone.

Hence we won't change the current behavior, and do not consider this to be a bug.
