### ISSUE TITLE
Introduce async / await

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#129]
### What is this feature about?

With wolkenkit 2.0, we introduced `async` / `await` to the backend, but the client SDK is still missing these new keywords. We should change this. Along with that, we should switch to the browsers' new Streams API, which in turn means to drop support for IE.

### What needs to be done to implement this feature?

- [x] Implement sending commands
- [x] Implement observing events
- [ ] Implement reading models
  - [ ] Support observing models
- [ ] Implement authorization
  - [ ] For commands
  - [ ] For events
  - [ ] For read models
- [ ] Add tests
- [ ] Update documentation

### What else should we know?

This issue is based on #86.

**Comment by gossi** [comment]
@goloroden was so kind to explain me the "special" or "virtual" events the server will send, when the command error, which are: `failed` and `rejected`. What's the state with them? If they will stay, I would have suggest something like this:

```
try {
  const open = await api.playing.game().open(…);
} catch(Rejected e) {
  // handle rejected case
} catch(Failure e) {
  // handle failure case
}
```

But that does not work, since the await Promise would be resolved once the command has been dispatched and the server responded with a 200. It thus will not have any knowledge about any further processing of the command given that time. Unless the _negative_ responses are given any _positive_ counterpart and the Promise is awaiting any of them. Then it might be running into a race condition, if the command dispatches any events and they will be emited before the _positive_ response is coming back. A hell lot of problems :D So I still want to share this, because async/await is often handled with try/catch and without further knowledge about the return value of the command, I would wrap the async call with try/catch, because it's what this code structure is for. I'll post it as food for thought, although I know it will be tricky to achieve ;)

**Comment by gossi** [comment]
Thanks for the explanation @goloroden - what kind of error will be catched with `ex` in your example? (If it is coming from `published`). Like, what will the content be?

**Comment by goloroden** [comment]
You‘ll get the reason what failed (either a timeout, if no matching event was received within time, or the cause of why things failed or were rejected).

**Comment by goloroden** [comment]
This issue has not been updated for > 1 year, and meanwhile we've got `async`/`await` literally everywhere. If we _should_ come up with a new client SDK at all, it will be built from scratch, and be using `async`/`await` pretty naturally. So closed.
