### ISSUE TITLE
Merge console into local.wolkenkit.io

### ISSUE THREAD

**Issue by gossi** [thenativeweb/wolkenkit#130]
### What is this feature about?

At the moment, the great console ist at https://console.wolkenkit.io/ where you need to connect it your local machine.

### What needs to be done to implement this feature?

- Put it in https://local.wolkenkit.io:3000
- Make three "sections/tabs" in the left bar: API Shell, Console, Info
- :)

### What else should we know?

It took me 2-3 weeks to find out about the console.

**Comment by goloroden** [comment]
What would be the benefit of having it included instead of having a centrally managed version?

**Comment by gossi** [comment]
Having everything in one place.

**Comment by goloroden** [comment]
To be honest, I assume that it's (currently) not worth the effort, since it requires a little more than just copying files from A to B 😉 

And the current solution works in exactly the same way, except you don't have it integrated in the management UI. But the only difference if you *had* it in the management UI would be a different url, anything else would stay the same. Hence we won't implement this, and I'm going to close this issue for now.

Of course, if you want to work on this, we would be happy about a PR 😊
