### ISSUE TITLE
Is it possible to run wolkenkit on Node.js 12?

### ISSUE THREAD

**Issue by IhostVlad** [thenativeweb/wolkenkit#1380]
### What is this question about?

I am trying to install wolkenkit example via `wolkenkit@4.0.0-ctp.6`, but `yarn`-ing in application folder causes following error: 
```
error wolkenkit@4.0.0-ctp.6: The engine "node" is incompatible with this module. Expected version ">=14.8.0". Got "10.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

According official release schedule https://nodejs.org/en/about/releases/, nodejs versions 10 and 12 are still supported. Okay, maybe version 10 is old enough (however it's subject to LTS until 2021-04-30), but what's wrong with version 12, which is active now and will be supported until 2022-04-30?

Known cloud computational services just had introduced Nodejs 12 and there is no support for Nodejs 14, so it cannot be launched in cloud. For instance AWS lambda had introduced version 12 less than year ago https://aws.amazon.com/ru/blogs/compute/node-js-12-x-runtime-now-available-in-aws-lambda/, and Azure Functions https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions has support only for 11 and 12 version in latest runtime

So limiting lower supported NodejS to version 14 looks very premature, because there are tons of services which have support only for Nodejs 12 version

**Comment by goloroden** [comment]
Hi @IhostVlad 👋 

Thanks for bringing up this issue. You are right that already requiring Node.js 14 today is somewhat early 😉 

Generally speaking, our overall strategy is to support the current LTS version, i.e. with our current stable release of wolkenkit we do support Node.js 12 (we do not support 10 any more, as this is actually quite old).

With wolkenkit 4 we decided to go with Node.js 14, since we are actually using features of 14, and wolkenkit 4 is not yet ready for production usage, but still in development. As Node.js 14 will become the new LTS in October 2020, and we don't expect wolkenkit 4 to be final before that, this aligns with our current strategy.

However, you brought up a valid point anyway: Node.js 14 is not yet supported very well by many cloud providers, so we should review what we are actually using from 14, and whether it's needed or whether it can be worked around by something which is compatible to Node.js 12.

We will have a look at this, and get back to you at a later point in time. I hope that this is fine for now.

**Comment by goloroden** [comment]
Hi @IhostVlad 😊 

As promised, I'm now getting back to this.

For now, we decided to stay with Node.js 14 as requirement, since we don't support platforms such as AWS Lambda or Azure Functions right now, but you have to provide a Docker image (or something installed on bare-metal) anyway, and then you can use Node.js 14 without any problems.

Once we are going to address FaaS scenarios in the future, we will, however, keep this in mind, that not all vendors immediately always provide the latest version, but that this may take some time.

So, for now I am going to close this issue.

Thanks anyway for bringing this up 😊
