### ISSUE TITLE
wolkenkit start fails when using symlinked packages

### ISSUE THREAD

**Issue by schmuto** [thenativeweb/wolkenkit#139]
### What is this bug about?
I'm using [lerna](https://github.com/lerna/lerna) to symlink local packages in the node_modules folder. This allows me to develop packages locally and use them in my project without publishing them on npm.
When I symlink a package in the `package.json` of my wolkenkit app, the `wolkenkit start`
 command fails with the following error message:
```
✗ Failed to restart the application.
  The command '/bin/sh -c cd /wolkenkit/app &&             npm install --production --silent' returned a non-zero code: 1

  ExecutableFailed: The command '/bin/sh -c cd /wolkenkit/app &&             npm install --production --silent' returned a non-zero code: 1

    at /Users/tobiasschmucker/Documents/git/helix/helix/helix-cloud/node_modules/wolkenkit/dist/shell/exec.js:26:18
    at ChildProcess.exithandler (child_process.js:278:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

### What steps are needed to reproduce the bug?

- `mkdir test-project && cd test-project`
- `npm init -f && npm i -D lerna && lerna init`
- `npx lerna create other-package -y` 
- `cd packages`
- `mkdir wolkenkit-app && cd wolkenkit-app && wolkenkit init` and choose chat template
- `npm i wolkenkit && npx lerna add other-package`
- `npx wolkenkit start`

### What is the expected result?

wolkenkit should resolve the symlinks in `node_modules` and import them as regular packages.

### What is the actual result?

wolkenkit fails to start and doesn't provide an error message.

### What else should we know?

- MacOS 10.14.3
- Node.js v10.14.2
- npm v6.4.1
- wolkenkit v3.1.0

**Comment by goloroden** [comment]
Hi @schmuto :-)

Thanks for bringing up this issue.

I'm afraid we won't be able to solve this, due to the way wolkenkit resolves npm modules. When you run `wolkenkit start`, the `node_modules` folder from your machine is actually *ignored*, and the CLI runs a fresh `npm install` inside the containers.

That's why we are only able to install things that are available from the network, but not locally from disk.

The reason why we do it this way is because the containers run Linux, but your host may be different, and some modules need recompiling for the target platform, so we can't just import your host's `node_modules` directory.

Unfortunately, this means that we can't support your use case 😢 
I'm very sorry for that.

**Comment by schmuto** [comment]
Alright, thanks for the info and explanation 👍
