### ISSUE TITLE
When is the aggregate state updated? May two commands be executed in parallel?

### ISSUE THREAD

**Issue by abego** [thenativeweb/wolkenkit#16]
In your Wolkenkit-Brochure you wrote on page 48:
 

>  calculate the new number of likes and add this information when publishing the liked event: 
> 
>     // ...
>     message.events.publish('liked', {
>       likes: message.state.likes + 1
>     });
>     // ... 
> 

 
 
Does the Wolkenkit framework ensure this also works correctly when two users are liking a message "at the same time"?
 
E.g. 
- users A and B see "0 likes" for message M
- both users "like" the message M ("at the same time)
- A's event is created with likes = 0+1
- B's event is created with likes = 0+1 (as `message.state.likes` is not yet updated)
- `message.state.likes` is updated to 1
- `message.state.likes` is updated to 1
- BUT: in the event store there are 2 likes for the given message, because two users liked it.
 
I think this boils down to the question when the state is updated, and if two commands may be executed in parallel.
 
 
Udo

**Comment by goloroden** [comment]
Hi @abego 😊 

Thanks a lot for your question!

Short answer: Yes, it works as expected.

Long answer: Yes, it works as expected, as wolkenkit serializes handling all commands. At the moment, this is global (so there is no parallel execution of commands that *could* be parallelized), but in the future we plan to change this, so that commands can be run in parallel, as long as they don't affect each other, i.e. as long as they do not refer to the same aggregate instance.

So, either way, the code works as expected 😊 

Hope this helps.

**Comment by goloroden** [comment]
@abego I don't know if you're still interested in this, but the latest developer build of wolkenkit now runs up to 256 commands in parallel, as long as they don't target the same aggregate (otherwise they are serialized to ensure consistency). This will be part of the next official release 😊
