### ISSUE TITLE
Named and ordered imports

### ISSUE THREAD

**Issue by ClemensSahs** [thenativeweb/wolkenkit#1672]
### What is this feature about?

moin moin,

I listen to both podcast from "programmierbar" with "goloroden" and I like the Idee behind wolkenkit.
And first I want give a **big thanks** for this nice work!

to the topic ->
I read some of the code and I was wondering about your import sorting. You focused you sort on the imported names and not the import source.
In my mind a sorting from "standard to local" ist much better. Perhaps we can discuss this.

```typescript
// current
import { ConfigurationDefinition } from './ConfigurationDefinition';
import { ConfigurationDefinitionItem } from './ConfigurationDefinitionItem';
import { processenv } from 'processenv';
import { Value } from 'validate-value';
```

```typescript
// expected
import { processenv } from 'processenv';
import { Value } from 'validate-value';

import { ConfigurationDefinition } from './ConfigurationDefinition';
import { ConfigurationDefinitionItem } from './ConfigurationDefinitionItem';
```

### What needs to be done to implement this feature?

- [ ] add internal namespaces and add them to tsconfig.json
- [ ] order imports from [standard to local](https://vxlabs.com/2020/10/06/sort-typescript-import-groups-from-standard-to-local/)

beste Grüße aus Hamburg

**Comment by goloroden** [comment]
Hi @ClemensSahs 👋

Thanks for bringing up this issue, and for taking the time to write in detail about your thoughts.

Actually, the way you suggest the ordering is how we did it in earlier times. However, meanwhile we‘ve come to the conclusion that in the end it doesn‘t matter where an import technically comes from, because first of all you care about what‘s imported. This is why we decided to do it this way.

Since in this case it can become difficult to decide which one goes first, if you use single and multiple imports, the import order is as follows:

- Single imports first
- Multiple import second
- Imports just for the sake of imports last

Inside of these blocks we order alphabetically.

Since this is the overall rule we use in all of our repositories, it‘s very unlikely that we are going to change this, especially given that it was an explicit decision to do it like it is now.

Anyway, thanks for your thoughts!

Have a nice evening,


Golo
