### ISSUE TITLE
How to authenticate a user

### ISSUE THREAD

**Issue by kuechlerm** [thenativeweb/wolkenkit#1674]
### What is this question about?
I copied a certificate.pem file from auth0 into the app folder and ran 

`npx wolkenkit dev --identity-provider-issuer https://xxx.eu.auth0.com/authorize --identity-provider-certificate .`

There is no redirect or anything - ClientMetadata.user.id is 'anonymous'.

1) I am unsure what I have to set `--identity-provider-issuer` to
2) what do I have to do to cause a login?

### What else should we know?
Using wolkenkit@4.0.0-ctp.6

Heard Golo in the programmier.bar podcast recently. The projects looks very interesting - I would like to try a realistic scenario. 
Thanks!

**Comment by goloroden** [comment]
Hi @kuechlerm 👋 

This is actually the desired behavior. Basically, those flags only specify which identity provider‘s tokens wolkenkit will accept. Since you typically approach wolkenkit via a programmatic HTTP call, it doesn‘t make sense to redirect – otherwise we would redirect an AJAX request 😉

So the backend only returns a `401`, but you have to handle this yourself in the client.

Regarding the two flags: You already used `—identity-provider-certificate` correctly, for `—identity-provider-issuer` you have to provide the value your identity provider puts into the `iss` claim of the tokens.

Does this help?

**Comment by kuechlerm** [comment]
Hey @goloroden ,
thanks for the response. I think I pass both flags correctly. On startup I can log the following 
```
  IdentityProvider {
    issuer: 'https://xxx.eu.auth0.com/',
    privateKey: undefined,
    certificate: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0d 0a 4d 49 49 43 2f 7a 43 43 41 65 65 67 41 77 49 42 41 67 49 4a 55 ... 1066 more bytes>,
    expiresInMinutes: 1440
  }
```

But all calls to any of the commands or views just work and return 200 and the expected data.
What am I missing here?

**Comment by goloroden** [comment]
Hey @kuechlerm 👋 

Sorry for the delayed response. The reason for this is that when you send a request *without* a token, the request is accepted as unauthenticated – and the command / query gets handled as usual. Whether it actually succeeds or not then depends on the `isAuthorized` callback.

You only get a `401` if you send an invalid or expired token.

Does that help to clarify things?

**Comment by kuechlerm** [comment]
Hi @goloroden,
thanks for your answer. I guess so.
I had to move on to other things, so I cannot try this out at the moment. Maybe I will come back at a later point.
Still looking forward to v4 and some docs. 

Thanks for the interesting work.
