### ISSUE TITLE
How to address authorization in v3.1

### ISSUE THREAD

**Issue by smiccoli** [thenativeweb/wolkenkit#2145]
It is my understanding that one of the new features that will be introduced in wolkenkit v4 will be authorization functions, in which I expect to implement arbitrary logic to define if the user is entitled to execute a command.

While im eager to put my hands on that release, Im now scratching my head around v3.1 as possible candidate for one of our applications. Based on its documentation, it seems that it is currently possible only to restrict to authenticated users, so my question is: how would it be possible to address use cases where only a given user group can trigger a command? (e.g. junior editor can trigger article.edit while only senior editors can trigger article.publish)

In our previous applications, the frontend client would communicate with a custom HTTP API layer that implemented all the authn/authz logic and then integrate with packages from Adriano Raiano for whatever concerns domain.

Many thanks and kudos for the project (and educational material on youtube)

**Comment by goloroden** [comment]
Hi @smiccoli 👋 

Thanks for bringing up this issue, and for your interest in wolkenkit – and of course, thanks as well for the nice words and the great feedback 😊

Your description of how authorization works in 3.x and 4.0 is correct, and it's also correct that the 4.0 version is way more flexible. Actually, since we are almost done with 4.0, I would not recommend to start developing with 3.x any more.

Anyway, taking 3.x as granted for the moment, the suggested solution would be to store things such as groups, roles, … in the identity provider, so that you get it as part of the user's token, and then check for the appropriate claims in the command handler.

This works, as long as you do not need dynamically set up groups at runtime (but talking about junior and senior editors, this seems to be pretty stable).

Does this help? (If not, please reach out to me via email to golo [dot] roden [at] thenativeweb [dot] io).

Have a nice day,


Golo

**Comment by smiccoli** [comment]
Indeed it clarifies a lot, as the user token was already including the user's groups and the solution in command handler looks quite simple.

Thanks a lot!

**Comment by goloroden** [comment]
Glad I could help 😊
