### ISSUE TITLE
Questions about Commands/Events

### ISSUE THREAD

**Issue by rdrey** [thenativeweb/wolkenkit#23]
Hi there!

I first heard about Wolkenkit on a podcast and again on Hacker News a few days ago, so I decided to read the brochure. (I've previously enjoyed Martin Kleppmann's talks around Event Sourcing / CQRS.)

I'm a little confused by a few details in the brochure at this point:

When the 'like message' command is defined, it is used to increment the number of likes and publishes that new like count in the event. Wouldn't it be cleaner if the command did only validation and the event did the actual state update (including calculating the new like count)?

I think I'm not 100% sure where to draw the boundary between command and event and why.

And about the authorization code: Why do both commands and events need to have authentication rules defined? I would have expected that only an authorized command can publish a matching event.

Very cool framework!
Rainer

**Comment by goloroden** [comment]
Hi Rainer,

first of all: Thanks a lot for your very nice feedback, and also for bringing up these questions 😊 

> When the 'like message' command is defined, it is used to increment the number of likes and publishes that new like count in the event. Wouldn't it be cleaner if the command did only validation and the event did the actual state update (including calculating the new like count)?

We modeled it this way, because the events should be idempotent. That means that if - for whatever reason - an event gets delivered multiple times, it shouldn't matter. If we increase by one in the event, the event is not idempotent any more, because suddenly the number of times it was delivered changes the result. That's why we calculate the new value already in the command, and use the event only for setting the new state.

> I think I'm not 100% sure where to draw the boundary between command and event and why.

It actually can be hard sometimes, but as a general rule of thumb I think the question for idempotency provides a good hint.

> And about the authorization code: Why do both commands and events need to have authentication rules defined? I would have expected that only an authorized command can publish a matching event.

It may make sense to have authorization configured differently for commands and events. E.g., only authenticated users are able to change the state (aka send commands), but everyone is allowed to see changes (aka retrieve events).

I hope this helps 😊

**Comment by rdrey** [comment]
Perfect, thanks. Feel free to close this :)

**Comment by goloroden** [comment]
😊
