### ISSUE TITLE
without @types/bson wolkenkit don't run for me

### ISSUE THREAD

**Issue by ClemensSahs** [thenativeweb/wolkenkit#2587]
### What is this bug about?
I install wolkenkit but with typescript and mongo we need types for bson, too?!?

### What is the expected result?
wolkenrun fine ;)

### What is the actual result?
```

⠙ node_modules/@types/mongodb/index.d.ts(45,78): error TS7016: Could not find a declaration file for module 'bson'. '..../wolkenkitchat/node_modules/bson/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/bson` if it exists or add a new declaration (.d.ts) file containing `declare module 'bson';`
node_modules/@types/mongodb/index.d.ts(57,111): error TS7016: Could not find a declaration file for module 'bson'. '..../wolkenkitchat/node_modules/bson/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/bson` if it exists or add a new declaration (.d.ts) file containing `declare module 'bson';`
✗ Failed to run the application.
```

### What steps are needed to reproduce the bug?

- `npx wolkenkit@4.0.0-internal.115 init`
- `cd ./projectname` ;)
- `yarn install`
- `npx wolkenkit@4.0.0-internal.115 dev`

### What else should we know?

with this after `yarn install` wolkenkit works as expected
- `yarn add @types/bson`

**Comment by goloroden** [comment]
Hi @ClemensSahs 👋 

Thanks for bringing up this issue 😊

I've tried to reproduce this, but on my machine, it works as it should. The only difference I can spot is that I have been using npm instead of yarn. Could you maybe try again with npm on your machine to see whether this is something specific to yarn?

Oh, and by the way: Which sample project and language did you use? I used the `chat sample` written in `TypeScript`, to test things.

**Comment by goloroden** [comment]
See #2603
