### ISSUE TITLE
Questions on Memory/Performance

### ISSUE THREAD

**Issue by pyros2097** [thenativeweb/wolkenkit#28]
How does wolkenkit store aggregates? Inmemory/database.
Does it replay all the events from the database everytime the sever starts up or loads it from a snapshot?
Does it cache the events/aggregates on the server then what happens if we run our of memory? Does it load only the hot data?
Does this implement something like Prevalent System Architecture?
How much of a performance boost will this architecture have over a normal MVC/CRUD app without caching at all?
Is there someway we can expose a REST API/ GraphQL api using wolkenkit as the data provider?

**Comment by goloroden** [comment]
> How does wolkenkit store aggregates? Inmemory/database.

wolkenkit stores the events that are used to build the aggregates in a database (the event store).

> Does it replay all the events from the database everytime the sever starts up or loads it from a snapshot?

It replays the events when an aggregate is loaded. It uses snapshotting per aggregate to improve performance, so that not all events need to be replayed every time.

> Does it cache the events/aggregates on the server then what happens if we run our of memory?  Does it load only the hot data?

It does not cache things in-memory. The only data in memory are the one you currently work with.

> Does this implement something like Prevalent System Architecture?

wolkenkit uses CQRS and event-sourcing.

> How much of a performance boost will this architecture have over a normal MVC/CRUD app without caching at all?

This can't be answered without any details, as this highly depends on the actual application. One benefit of wolkenkit is that you will never need to do any `JOIN`s when reading data, so this *might* be faster than a typical CRUD application, but YMMV.

> Is there someway we can expose a REST API/ GraphQL api using wolkenkit as the data provider?

Yes, there is a REST and a websocket endpoint. GraphQL is currently not supported.
