### ISSUE TITLE
Docker for Windows using Hyper-V

### ISSUE THREAD

**Issue by Pandaros** [thenativeweb/wolkenkit#3]
I'm using Docker for windows like the Docker inc. suggested  [url](https://docs.docker.com/docker-for-windows/install/)

Is it possible to add an installation guide like the "Installing using Docker Machine" but for "Installling using Docker with Hyper-V"?

**Comment by goloroden** [comment]
Thanks for your interest in wolkenkit 😊 

Unfortunately, I have to admit that none of us has experience with Docker and Windows, hence I will need to ask a few (probably quite naive questions):

- Is `Docker for Windows` and `Docker with Hyper-V` the same thing?
- With your setup, do you run Linux containers, or Windows containers (e.g. based on Nano server)?

It would help us to get a better feeling for what needs to be done to run wolkenkit on Windows.

**Comment by Pandaros** [comment]
Thank you for your quick response. 

  * Yes Docker for Windows is using Hyper-V. 
  * We are working only with Linux containers.

**Comment by goloroden** [comment]
Okay, this helps me to get started.

We need to figure out how this works, and - first of all - we need to setup a machine with Windows 10 to be able to reconstruct things.

Until we are ready with this, there *may* be a workaround (I haven't tested it, it's just a guess): Is it possible to address Docker for Windows from the Linux subsystem, e.g. from `bash`? I *think* that this should be doable.

If so, you would need to do the following:

- Install and run Docker for Windows
- Enable the Linux subsystem
- Run `bash`
- Set the `DOCKER_HOST` environment variable to the desired string
- In case Docker for Windows is using a certificate, also set `DOCKER_TLS_VERIFY` and `DOCKER_CERT_PATH`
- If Docker for Windows is not reachable as `localhost` from `bash` configure the appropriate IP address as `local.wolkenkit.io` in your `C:\Windows\system32\drivers\etc\hosts` file

I would be very interested in whether you get this scenario up and running. Additionally, we will have a look at it, but this may take us a while.

**Comment by appelgriebsch** [comment]
Hmmm tried the following on Docker for Windows:

* open Windows 10 command prompt
* run `docker-machine create --driver hyperv wolkenkit`
* wait for docker-machine to boot up
* install Bash on Ubuntu for Windows
* install wolkenkit-cli as described in the Getting Started Guide
* install nodejs as described in the Getting Started Guide
* setup aliases for docker.exe and docker-machine.exe (e.g. `alias docker-machine="/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-machine.exe"`)
* run `eval $(docker-machine env wolkenkit)`
* check environment variables with `export`
* create wolkenkit chat sample as described in Getting Started Guide
* try to start application via `wolkenkit start` in the chat folder

Wolkenkit-CLI will complain about not being able to talk to DOCKER_HOST as IP address is IPv6 instead of IPv4 for Docker on Windows.

Tried to introduce IPv6 mapping to local.wolkenkit.io to /etc/hosts on Bash on Ubuntu for Windows. Still same issue: `~/chat$ wolkenkit start
✗ Host local.wolkenkit.io specified in package.json could not be resolved. No IPv4 Address found.`

Currently lost. Don't know how to configure Hyper-V to issue IPv4 addresses for NAT(ted) Network adapters.

**Comment by goloroden** [comment]
@appelgriebsch Thanks for sharing your insights!

Actually, independent of you, we have started today to evaluate how to get wolkenkit running on Windows, so maybe we can share some progress here within the near future…

**Comment by appelgriebsch** [comment]
If I can support in some way, pls. let me know.

**Comment by goloroden** [comment]
Thanks, that's very nice of you 😊

**Comment by grundhoeferj** [comment]
Hello @Pandaros @appelgriebsch :-) 
we have successfully run wolkenkit on Windows Hyper-V.  Now we have to do some internal tests and improvements.

@appelgriebsch Your instructions helps us a lot, special thanks to you!

Does anyone of you have time and pleasure to test our documentation? :-)

**Comment by appelgriebsch** [comment]
Yeah, me... just point me to it and I will have a look later :)

**Comment by grundhoeferj** [comment]
@appelgriebsch You've got mail :-)

**Comment by goloroden** [comment]
@Pandaros @appelgriebsch Finally, we have updated the documentation. There is now a dedicated page [Installing on Windows](https://docs.wolkenkit.io/latest/getting-started/installing-wolkenkit/installing-on-windows/) 🎉 

If you have the time it would be really great if you could have a look at it, and double-check whether it works for you. If so, we could then close this issue 😊

Do you think that you could try it and give us some feedback on this?

PS: There now is also an additional page on [Verifying system requirements](https://docs.wolkenkit.io/latest/getting-started/installing-wolkenkit/verifying-system-requirements/).

**Comment by appelgriebsch** [comment]
Looks pretty good so far... might be a little to much 'restarts' (but on Windows you never know ;)). The chapter for "Setting up Git" is likely obsolete (it is available right after installing Bash on Ubuntu on Windows. Additionally the steps for "apt-get" need superuser permission and have to be prefixed with 'sudo'. Also, NVM created the default alias on my machine automatically.

Most importantly though: the statement `sudo sh -c 'echo $(docker-machine ip wolkenkit)\\tlocal.wolkenkit.io >> /etc/hosts'` doesn't work as expected. I just updated the /etc/hosts automatically with vi for the moment.

After some tests it looks like changes to the /etc/hosts will not be persisted and everytime you restart the Bash On Ubuntu On Windows it is reverted to the initial version. I'm still looking into it.

**Comment by grundhoeferj** [comment]
@appelgriebsch Thanks for the support! 😊
"Setting up GIT" - we had to this on *Bash on Ubuntu on Windows* in Windows 10 Build 1607. So it is now obsolete, because Windows 10 Build 1703 is required.

The statement `sudo sh -c 'echo $(docker-machine ip wolkenkit)\\tlocal.wolkenkit.io >> /etc/hosts'` also does not work on my machine. It ends with this error: `bash: /etc/hosts: No permissions`
But the problem with persisting data inside the `/etc/hosts` file does not affect on my machine. Could you find something?

**Comment by goloroden** [comment]
I think that we will need to re-run what's currently described in the documentation a few times on a newly created VM from scratch to figure out what the behavior of a vanilla Windows is.

@appelgriebsch We will keep you informed 😊

**Comment by goloroden** [comment]
@Pandaros Have you seen the latest update of the documentation which now also explains [how to install wolkenkit on Windows](https://docs.wolkenkit.io/latest/getting-started/installing-wolkenkit/installing-on-windows/)?

**Comment by appelgriebsch** [comment]
some small hints:

- after installing nvm (via `curl http://... | bash`) you should put the message bubble to restart Bash on Ubuntu on Windows (it is required due to changes on .bashrc by the installer of nvm)
- doing an` nvm install 8.2.1` registers this version as default automatically (no manual step required)
- the command line `sudo - sh -c -e "echo '$(docker-machine ip wolkenkit)\\tlocal.wolkenkit.io' >> /etc/hosts"` isn't working and might be replaced with `sudo -**E** sh -c -e "echo '$(docker-machine ip wolkenkit)\\tlocal.wolkenkit.io' >> /etc/hosts"`
- you should hint that the changes to /etc/hosts requires supervisor access and the command could be `sudo -E vi /etc/hosts`

Otherwise it works pretty well right now.

**Comment by goloroden** [comment]
@appelgriebsch Thanks for your feedback! We'll adjust the documentation accordingly, and let you know, once we have done this 😊

**Comment by goloroden** [comment]
Finally, we have finished the work on the documentation, so an official guide to [install wolkenkit on Windows](https://docs.wolkenkit.io/latest/getting-started/installing-wolkenkit/installing-on-windows/) is now available 🎉 

Thanks a lot to @appelgriebsch for the great feedback and testing 😊 

The updated documentation will also be part of our next release.

**Comment by blumatixgs** [comment]
I followed the instructions [install wolkenkit on Windows](https://docs.wolkenkit.io/1.1.0/getting-started/installing-wolkenkit/installing-on-windows/) till the end and managed to install Docker (17.09.0-ce) on my windows 10 machine.

Also I  successfully created a wolkenkit vm on hyper-v with the `docker-machine` command. It is possible to ping it with `local.wolkenkit.io` from bash and commandline.
I installed nvm, node 6.11.2 and the latest wolkenkit  (V0.1.4).

I created a demo project with the `wolkenkit init` command. When running it with `npm run start` I got the following error:

>   Starting the application...
>   Docker client is not installed.
> ✗ Failed to start the application.
> ...


There is no docker image listed and docker ps shows no container. What did I miss?

**Comment by grundhoeferj** [comment]
@blumatixgs thank you for your interest in wolkenkit 😊

It seems that the `docker` client command is not installed/available. Can you please double check this, with the following command on your terminal: `docker version`. If this command failed, then please check the section "Aliasing docker commands" in our docs: https://docs.wolkenkit.io/1.1.0/getting-started/installing-wolkenkit/installing-on-windows/#aliasing-docker-commands
Did that help you? 🤔

**Comment by blumatixgs** [comment]
@grundhoeferj thanks for your help. The `docker` command is available also `docker-machine `which creates the `wolkenkit` vm on hyper-v.
```
$ docker version
Unable to translate current working directory. Using C:\WINDOWS\System32
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
~/.bashrc:
```
...
alias docker="/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker.exe"
alias docker-machine="/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-machine.exe"
alias docker-compose="/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-compose.exe"
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.137.210:2376"
export DOCKER_CERT_PATH="/mnt/c/Users/Günter/.docker/machine/machines/wolkenkit"
export DOCKER_MACHINE_NAME="wolkenkit"
export COMPOSE_CONVERT_WINDOWS_PATHS="true"
# Run this command to configure your shell:
# eval $("C:\Program Files\Docker\Docker\resources\bin\docker-machine.exe" env --shell bash wolkenkit)

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$PATH:$HOME/.wolkenkit"
```

**Comment by grundhoeferj** [comment]
@blumatixgs Thanks for your fast response 😊 
I found the problem in the wolkenkit CLI. Currently we rewrite the wolkenkit CLI and there is a problem with command detection on Windows systems. If this issue is fixed, i will give you feedback.

**Comment by blumatixgs** [comment]
@grundhoeferj thanks for this information. Let me know if I could help by testing something.

**Comment by goloroden** [comment]
Hi @blumatixgs, hi @grundhoeferj 😊 

First of all, thanks for bringing up this issue! I am very sorry that you had problems, since this is especially bad when just getting started… to provide a little bit of background: In the past, our CLI was written in Go, and this was the implementation used for creating the documentation. We are currently transitioning to a complete rewrite of the CLI, this time in Node.js. The install script had already been updated, so you already got the new version - but this has not yet been reflected in the documentation, and apparently we didn't test it well enough on Windows. Again, I am very sorry for that 😢 

As I have seen, @grundhoeferj has already taken care of the problem and created a PR for that. This PR is currently assigned to me for review, but I am still on the road (I have been on the road all day), so I won't make it to merge it today - but this will be the first thing I am going to look at tomorrow morning.

So, the issue can hopefully be solved quickly. Sorry again for all the problems you had, and either @grundhoeferj or I (or both of us 😉) will provide you with updated news once it is merged.

**Comment by goloroden** [comment]
@grundhoeferj I have merged it (yes I know, it's not yet tomorrow, but I couldn't wait 😉).

**Comment by goloroden** [comment]
@blumatixgs We have release an updated version of the CLI (version `0.1.5`). This *should* solve your problems. Would you mind checking this?

You can easily update to the new version using

```shell
$ npm install -g wolkenkit
```

**Comment by blumatixgs** [comment]
@goloroden I did the hole installation process from the documentation on my pc at home and installed wolkenkit version 0.1.5.

When starting the `wolkenkit init` project with `npm run start` I got the same error as on my machine in the office.

```
zgue@WSX99A:/mnt/c/tmp/demo2$ npm run start

> wolkenkit-template-chat@1.0.0 start /mnt/c/tmp/demo2
> wolkenkit start && http-server ./client/ -o

  Starting the application...
  Docker client is not installed.
✗ Failed to start the application.

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/home/zgue/.nvm/versions/node/v6.11.2/bin/node" "/home/zgue/.nvm/versions/node/v6.11.2/bin/npm" "run" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wolkenkit-template-chat@1.0.0 start: `wolkenkit start && http-server ./client/ -o`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wolkenkit-template-chat@1.0.0 start script 'wolkenkit start && http-server ./client/ -o'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wolkenkit-template-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wolkenkit start && http-server ./client/ -o
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wolkenkit-template-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wolkenkit-template-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/tmp/demo2/npm-debug.log
zgue@WSX99A:/mnt/c/tmp/demo2$ wolkenkit --version
  0.1.5
```
No docker image is created no docker container is running.
I can ping `local.wolkenkit.io` from bash and command shell.

My ~/.bashrc looks like
```
...
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
alias docker="/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker.exe"
alias docker-machine="/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-machine.exe"
alias docker-compose="/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-compose.exe"
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://10.0.0.17:2376"
export DOCKER_CERT_PATH="/mnt/c/Users/LocalUser/.docker/machine/machines/wolkenkit"
export DOCKER_MACHINE_NAME="wolkenkit"
export COMPOSE_CONVERT_WINDOWS_PATHS="true"
# Run this command to configure your shell:
# eval $("C:\Program Files\Docker\Docker\resources\bin\docker-machine.exe" env --shell bash wolkenkit)

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$PATH:$HOME/.wolkenkit"
```

For your information, I have not much knowledge about Linux on Windows or Linux itself.

**Comment by goloroden** [comment]
I'm very sorry to hear that it doesn't work yet 😢 

I'm afraid that we will have to wait for @grundhoeferj then, as he has a Windows PC at hand and did all the testing. I think that we will have progress here on Monday. Sorry for the delay.

**Comment by grundhoeferj** [comment]
@blumatixgs We have good news for you: with some bugfixes we no longer need the Linux-Subsystem. Now we are using the PowerShell 😊 
For that we have adjust our documentation. The documentation will go live in the next hours. Currently you can try it with the help of this link: https://github.com/thenativeweb/wolkenkit-documentation/blob/master/src/docs/1.1.0/getting-started/installing-wolkenkit/installing-on-windows/index.md

Sorry for the delay! I hope now everything works!? 🤔

**Comment by goloroden** [comment]
@blumatixgs @grundhoeferj The updated documentation is now live.

**Comment by blumatixgs** [comment]
@grundhoeferj @goloroden Thanks, I will try it out this afternoon.

**Comment by goloroden** [comment]
I'm really looking forward to whether it works for you!

And, btw, thank you so much for the time you spend on this 😊

**Comment by blumatixgs** [comment]
First of all I think you are waiting for this:
![image](https://user-images.githubusercontent.com/32864490/31894604-39c786a4-b80f-11e7-868e-b397d008ee1e.png)

The installation is now much simpler! I did not install version 1.1.0 as mentioned in the new documentation. I installed the latest version (v0.1.5).

After creating the demo project with the `wolkenkit init` command the `npm run start` did not work, I got an error. I solved the problem by calling `wolkenkit start`. That pulled a lot of things and after that `npm run start` worked.

FYI: When I reboot my machine and want to start the demo again, I have to run 'wolkenkit stop' because it's running already but is not connectable by the browser.

Thanks for your effort!

**Comment by goloroden** [comment]
Great to hear that it (basically) works 🎉 
This is really great news!

Regarding the CLI version number: Yes, you are right, the current version is `0.1.5`. This will be fixed within the next days, and then there will also be the `1.1.0` as expected. This is because we are currently transitioning from an old CLI (which was written in Go) to a modern one (which is written in Node.js), and we need to make sure that everything works before we fix the version number matching the runtime version on npm.

Regarding the `npm run start` script - that's really strange. We will have a look at this tomorrow.

Regarding the reboot - that's strange as well. We will have a look at this, too.

**Comment by goloroden** [comment]
Since the installation on Windows is up and running again, I'm going to close this issue now and transfer the minor issues that are left into new issues.
