### ISSUE TITLE
Simple view not found in blank project for v4 ctp 6

### ISSUE THREAD

**Issue by kostadinnm** [thenativeweb/wolkenkit#3015]
### What is this bug about?
Upon executing `wolkenkit dev` there's a runtime error complaining SampleView must have some props.

### What is the expected result?
GraphQL schema validation shouldn't prevent you from running the server.

### What is the actual result?
The dev server doesn't run.

### What steps are needed to reproduce the bug?
Just run the `init` and `dev` commands, picking the "blank" template(either javascript or typescript).

### What else should we know?
Ideally the whole blank template should provide a "sample" aggregate and pipe it across "domain", "flows", "hooks", "infrastructure", "notifications" and "views" OR at least return a single expected property from `getResultItemSchema()`:
```
...
properties: {
          id: { type: 'string' }
      },
```
That last think proved to work ok for both js and ts. If ok, I might initiate a pr, so let me know..

Here's a screenshot of the error:
![2022-11-25_19-33](https://user-images.githubusercontent.com/18436405/204035221-652cd4a3-a2e6-4bee-a0d5-48c26429fff9.png)

Kind regards,
Kostadin

**Comment by kostadinnm** [comment]
@goloroden, could you add me to the contributors, if this fix is ok?! I guess that is the only way I could issue a pull request?!

**Comment by goloroden** [comment]
Hi @kostadinnm 👋 

Thanks for bringing up this issue.

Actually, the current behavior is correct "by design", since the `blank` template doesn't represent a runnable application, it should just provide you with the required file and folder structure to get started.

It's – by intention – not a complete application, and hence can't be run without any changes.

Since we want to keep the `blank` template as minimal as possible, unfortunately there is no option to change this behavior (and the error is correct: Having a view without fields doesn't make sense, so it fails to run).

However, thanks for reporting this 😊
