### ISSUE TITLE
New command function does not exist?

### ISSUE THREAD

**Issue by sscholle** [thenativeweb/wolkenkit#33]
I've added a new command to the chat template app called 'comment'.

It's supposed to add comments to chat messages. I've setup all the command, event and model things to reflect this.

However the UI complains in the console that my comment function does not exist.
Here it is, i've added it to the `commands` object:
<pre>
  comment (message, command, mark) {
    message.events.publish('commented', {
      comments: message.state.comments.push(command.data.comment)
    });

    mark.asDone();
  }
</pre>

The Error (if that helps):
<pre>
index.js:28 Uncaught TypeError: chat.communication.message(...).comment is not a function
    at HTMLUListElement.view.messages.addEventListener.event
</pre>

**Comment by goloroden** [comment]
Have you tried logging out of the console and re-connecting again?

The console only reads the application's configuration when initially connecting, so this may be the reason why.

Another thing to try out: If you connect to the `https://local.wolkenkit.io:3000/v1/configuration.json` endpoint of your application, does the JSON listed there contain your new command?

**Comment by sscholle** [comment]
the endpoint responds with:

<pre>
{
    "writeModel": {
        "communication": {
            "message": {
                "commands": {
                    "send": {},
                    "like": {},
                    "transferOwnership": {},
                    "authorize": {}
                },
                "events": {
                    "sent": {},
                    "liked": {},
                    "transferredOwnership": {},
                    "authorized": {},
                    "sendFailed": {},
                    "sendRejected": {},
                    "likeFailed": {},
                    "likeRejected": {},
                    "transferOwnershipFailed": {},
                    "transferOwnershipRejected": {},
                    "authorizeFailed": {},
                    "authorizeRejected": {}
                }
            }
        }
    },
    "readModel": {
        "lists": {
            "messages": {}
        }
    }
}
</pre>

The issue was resolved by running `wolkenkit reload`

**Comment by sscholle** [comment]
Is it normal to run `wolkenkit reload` each time commands are added?

**Comment by goloroden** [comment]
Yes. A code change requires a reload or a restart of the application. 

For more details see https://docs.wolkenkit.io/1.2.0/reference/using-the-cli/controlling-the-lifecycle/#restarting-an-application

**Comment by sscholle** [comment]
Surely a different command should exist to update the code and re-init instead of recreating the images each time, I know it amounts to the same thing, but it would be faster to copy new code into the docker images?
It just seems like a poor workflow for development

**Comment by goloroden** [comment]
Basically, I agree with you.

Right now we have two problems in implementing this:

1. A code change may also include changes to `package.json`, so we need to re-run `npm install`. We have explicitly decided *not* to copy the `node_modules` folder from the host to the container, as this could result in OS-specific conflicts, especially when using binary modules. So at least in some scenarios we definitely need to rebuild the containers.
2. We don't work with volumes so far. Of course this would be an option to at least avoid having to rebuild the container as long as the `package.json` file has not changed. Unfortunately, once we add the application directory as a volume, we also implicitly add the `node_modules` folder as part of that volume, and we have a problem with what I described above. Of course, we could clean it, and re-install anyway, but then we would also change your files on the host. And this is a thing that we definitely wanted to avoid.

What would be extremely helpful here would be the ability to mount a volume, but to exclude subdirectories from the volume. There are some hacks for this (such as mounting an empty directory for the subdirectory), but AFAIK no official approach.

But anyway, since it's been quite some time since we last discussed this, it might be a good idea to have a look what's possible right now.

**Comment by goloroden** [comment]
PS: We'll put this on our list of things to do in one of the next sprints, so please give us a little time, but hopefully it should get better soon 😊
