### ISSUE TITLE
Namespace wolkenkit on GitHub, NPM

### ISSUE THREAD

**Issue by coderbyheart** [thenativeweb/wolkenkit#4]
This will make it easier to identify which packages (officially) belong to wolkenkit.

- [ ] move the packages to the https://github.com/wolkenkit organization 
- [ ] [scope the packages](https://docs.npmjs.com/misc/scope) on NPM under `@wolkenkit`

**Comment by goloroden** [comment]
Thanks a lot for bringing this up 😊 

For now, we have decided to keep the packages at the `thenativeweb` organization, as this makes managing repositories easier for us (there are some private ones, and we don't want to have some here, some there, and we also don't want to have two organizations that we need to pay for).

With npm, I get your point, but since this would be a breaking change for all already published modules, we will keep it as it is for now. I don't say that we won't do it at a later point in time, maybe as part of another major release.

**Comment by goloroden** [comment]
I'm moving this to our internal issue tracking, hence I'm going to close this here.

@coderbyheart Once we do this, we'll let you know 😊

**Comment by gossi** [comment]
Actually, this is quite important for #92 as the types should mimic the packages. For example, I initially typed the module `wolkenkit` for the server package, but actually this is `wolkenkit-core` so my typings were (and still are) wrong, since they don't map to the appropriate package. (I later found out about https://docs.wolkenkit.io/3.1.0/getting-started/understanding-wolkenkit/architecture/).

I truly support the move to a`@wolkenkit` organization. This way, you can easily put it this way: "Everything within `@wolkenkit` is there to run your app" whereas everything that starts with `wolkenkit-*` (eg. `wolkenkit-boards`) is related to it but not meant to be needed to develop your application.

Also I may suggest, that `wolkenkit` should be `@wolkenkit/cli` (to make it more specific! it really tricked me since most other frameworks follow these patterns: `@framework/cli` rsp `framework-cli`) and `wolkenkit-core` could be rethought as `@wolkenkit/server` (to better run the semantics of the client and server pair).
