### ISSUE TITLE
Check whether aeonstore is used in the wrong places

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#564]
### What is this task about?

For 4.0, we named a few interfaces `aeonstore`. Maybe we went too far with this, e.g. maybe with the Docker images and / or the environment variables. We should verify and fix this, if needed.

### What needs to be done to complete this task?

- [x] Figure out where `aeonstore` is being used as a term
- [ ] Verify if there are wrong usages
- [ ] Fix the wrong usages

### What else should we know?

This should be done either by @goloroden, or at least with @goloroden.

**Comment by yeldiRium** [comment]
The places where the term `aeonstore` is currently used are:

- the Aeonstore implementation
- the domain process in the microservice runtime
- the cli command that generate the docker-compose manifests

Since the Aeonstore __is__ it's http interface and is an abstraction over multiple different database implementation, I'd argue that the current uses are all correct. The domain process is intended to always be used with an actual Aeonstore, which will still work after we've extracted the Aeonstore to its own code base. And from this follows that the docker-compose manifests should contain the term as well.

I think this should stay as it is. @goloroden: What do you think?

**Comment by goloroden** [comment]
Sounds reasonable, and thanks for verifying 👍
