### ISSUE TITLE
Support directories next to server

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#784]
### What is this bug about?

Right now, when adding a directory next to `server`, the directory structure in `build` changes (since it does not only contain the server folder, but now another layer on top of that). This breaks the build. We should fix this.

### What is the expected result?

A wolkenkit application should be runnable, no matter if there are additional folders or not.

### What is the actual result?

A wolkenkit application is only runnable, if there are no additional folders besides `server`.

### What steps are needed to reproduce the bug?

- Create a new wolkenkit application
- Add a `test` folder next to `server`
- Try to run the application

### What else should we know?

This issue was brought up by @damienbenon, so we should notify him once this has been fixed.

**Comment by yeldiRium** [comment]
Hi @damienbenon,

does this issue still persist? I've tried to reproduce it with the newest public wolkenkit version (`4.0.0-ctp.1`), which by now creates an additional folder on the top level (`deployment`) when initializing an application. Additionally I've created a `test` directory with some `.ts` files in it.

With the `tsconfig.json` that is provided with the test applications, this problem does not seem to occur.

**Comment by damienbenon** [comment]
Hi @yeldiRium, you're right, this does not happen with the default `tsconfig.json` (sorry, I missed that point in the reproducer).

In my case this `tests` directory was included in tsconfig as follows:

```json
{
  "compilerOptions": {
    "sourceMap": true,

  },
  "include": [
    "./server/**/*.ts",
    "./tests/**/*.ts"
  ]
}
```

Which outputs then `build/server` and `build/tests` on compile (instead of flattening directly the content of the `server` directory into `build`).

So actually there is no problem here, unless you allow users to touch `include` configuration.

TBH I don't know if this issue should be considered.

As long as you let this power to the user, one that includes another directory will face same troubles. 

However the error message states most of the problem (you still have to look at the `build` directory to understand that the structure doesn't match the path to load the application):

```js
{
  ex: {
    name: 'DirectoryNotFound',
    code: 'EDIRECTORYNOTFOUND',
    message: 'Directory \'<app>/build/domain\' not found.',
    cause: undefined,
    data: undefined,
    stack: 'DirectoryNotFound: Directory \'<app>/build/domain\' not found.
    at Object.getDomainDefinition (/Users/dbenon/projects/perso/wolkenkit-slack-test/node_modules/wolkenkit/build/lib/common/application/getDomainDefinition.js:20:15)
    at async Object.getApplicationDefinition (/Users/dbenon/projects/perso/wolkenkit-slack-test/node_modules/wolkenkit/build/lib/common/application/getApplicationDefinition.js:34:30)
    at async /Users/dbenon/projects/perso/wolkenkit-slack-test/node_modules/wolkenkit/build/lib/runtimes/singleProcess/processes/main/app.js:31:39'
  }
}
```

**Comment by goloroden** [comment]
@damienbenon Ah, I see – thanks for clarifying this!

> As long as you let this power to the user, one that includes another directory will face same troubles.

TBH I think we should support this case, as having a test directory definitely makes sense! (And I can think of a bunch of other things that may be helpful here, so we shouldn't get into the user's way here.)
