### ISSUE TITLE
wolkenkit development on "windows 7"

### ISSUE THREAD

**Issue by kostadinnm** [thenativeweb/wolkenkit#95]
Hello.
Is there a reason why wolkenkit is allowed to run only on windows 10 versions 1703 or above?! I've been trying to run it on a spare windows 7 virtual machine, but it says "docker client not installed". I'm expecting it to run without any special dependencies on any Node.js environment, but in [Verifying system requirements](https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/verifying-system-requirements/) it says: 

> Windows 10 Professional, Enterprise, or Education (build 1703 or above)

Of course, I'll test it on a win10 ver>1703 later, but I wonder whether that docker-client-not-installed message is related. If so, a better output may be shown.
Here is my package.json content:
```json
{
    "name": "chat",
    "version": "0.1.0",
    "description": "wolkenkit demo",
    "dependencies": {
        "wolkenkit": "^2.0.0"
    },
    "wolkenkit": {
        "application": "chat",
        "runtime": {
            "version": "latest"
        },
        "environments": {
            "default": {
                "api": {
                    "address": {
                        "host": "local.wolkenkit.io",
                        "port": 3000
                    },
                    "allowAccessFrom": "*"
                },
                "node": {
                    "environment": "development"
                }
            }
        }
    },
    "keywords": [
        "wolkenkit"
    ],
    "license": "AGPL-3.0"
}
```

Here is the output I get from `npx wolkenkit start`:
```powershell
 Starting the application...
  Docker client is not installed.
✗ Failed to start the application.
  ExecutableNotFound
    at new CustomError (C:\Users\<user>\Projects\demo\chat\node_modules\defekt\dist\defekt.js:44:116)
    at Object._callee$ (C:\Users\<user>\Projects\demo\chat\node_modules\wolkenkit\dist\wolkenkit\commands\shared\checkDocker.js:68:19)
    at tryCatch (C:\Users\<user>\Projects\demo\chat\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\<user>\Projects\demo\chat\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\<user>\Projects\demo\chat\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\<user>\Projects\demo\chat\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\<user>\Projects\demo\chat\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```

Btw, my goal is to simply build the chat example w/o that webpack-clutter. I don't want any CLIs as well.

Cheers,
Kostadin

**Comment by goloroden** [comment]
Hi @kostadinnm 😊 

Thanks for bringing up this question. The reason why you need at least Windows 10 with the given build is that wolkenkit – as the message suggests – requires Docker, and AFAIK Docker does not work on Windows versions less than 10.

To find out how to setup wolkenkit correctly you might be interested in [installing on Windows](https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/installing-on-windows/), and then in following the [getting started guide](https://docs.wolkenkit.io/2.0.0/guides/creating-your-first-application/setting-the-objective/).

Does this help?

**Comment by kostadinnm** [comment]
Yep, I glanced at those. I'd rather be pointed to a technical explanation why wolkenkit requires it.
I'm in a process of finding whether my cpu has a thing called SLAT(second level address translation) in order to run docker.
It would be sad if getting into wolkenkit is hindered by such requirements.

**Comment by goloroden** [comment]
The main (technical) reason why we require Docker is because it makes life so much simpler for everyone involved: To run, wolkenkit does not only start a number of Node.js processes, but it also requires a bunch of infrastructure (a MongoDB for the read database, a PostgreSQL for the write database, a RabbitMQ as message queue), and if we asked everyone to install these things manually, probably nobody would do so. Using Docker helps us here dramatically, because the CLI is able to download and run everything on your behalf, without requiring any other interaction.

Besides, it also helps us to ensure that you have the correct Node.js version installed, that you have the correct dependencies, and so on …

And: It provides a portable environment, so that you know that if it works here, it will work there. And it will work on Kubernetes as well, on AWS, Azure & co.

In the end, it comes down to the question: For the typical user / developer of wolkenkit, what is worse? Having to install Docker? Or having to install and setup and configure MongoDB, PostgreSQL and RabbitMQ? And if something goes wrong, what is easier to maintain and support? From out POV the answer is pretty clear here 😉 

If you don't want to install Docker on your machine, you may use a virtual machine. Have you seen https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/installing-using-vagrant/ ?

**Comment by kostadinnm** [comment]
Thanks for the extensive answer. It is fascinating how combining all those sub-platforms makes for a promising frame to build on.
On the vagrant clue - I've been reading this as well, but it's hard for me to justify what route to go for. As to what I read, docker is container tech on top of one's OS, while vagrant is easier to setup, a bit slower but has stronger isolation.

**Comment by goloroden** [comment]
Thanks for the nice words 😊 

Regarding Docker vs Vagrant, I think this is exactly the decision you need to take: Do you prefer a lightweight solution that integrates with your OS, or do you prefer a more heavyweight, but isolated approach?

**Comment by goloroden** [comment]
PS: Did this answer your questions? If so, would you mind to close this issue?

**Comment by kostadinnm** [comment]
Sure
