### ISSUE TITLE
Wolkenkit 4 documentation

### ISSUE THREAD

**Issue by dfeyer** [thenativeweb/wolkenkit#980]
### What is this question about?

Hi, i see good docs for the preview version of the framework, did you have any, even unfinished, documentation about the upcoming 4.0 release. By the way the framework looks really promising. 

### What else should we know?

I'm currently pushing ES/CQRS at my current organisation and need to prototype a POC to see how Wolkenkit can help us. Did you have any deadline for the 4.0 ? If we can invest on top of your framework I will be really glad to help where I can.

**Comment by goloroden** [comment]
Hi @dfeyer 😊 

Thanks for bringing up this issue! Right now, unfortunately, we do not yet have any documentation on 4.0 available. The only reference so far is wolkenkit's [README.md](https://github.com/thenativeweb/wolkenkit/blob/master/README.md) file, which along with the TypeScript types help, if you know the concepts from 3.x … but this is definitely not how it should be.

We actually started yesterday (literally!) to discuss the structure for the 4.0 documentation, so we will address this soon, and our goal is to have documentation ready before the final version, probably for CTP 5, which should (current guessing) be there around August or September.

As you've asked for a deadline for 4.0 – we don't have one. We follow the "it's done when it's done" approach, and it's more important to us to get the product right, than to have a fixed delivery date, which if in doubt has a negative impact on quality.

However, the current estimation is:

- CTP 3: Will include flows, should be there ~ July 10th.
- CTP 4: Will include views, should be there end of July.
- CTP 5: Will include documentation, blob storage, more details, ~ August / September.

Maybe CTP 5 will be called RC 1, but we'll need to wait and see …

However, to get started now I guess your best bet is to join the [wolkenkit Slack channel](http://slackin.wolkenkit.io/), where we can help you with specific issues, and support you in getting started with 4.0 CTP versions quickly.

Besides, since you mentioned that you might be able to help, if you want to, let's talk about possible options in detail. Can you please contact me via mail at `golo [dot] roden [at] thenativeweb [dot] io`?

Have a nice weekend,


Golo

**Comment by goloroden** [comment]
Closed due to inactivity.
